# Site settings
title: test
email: ymh9509@163.com
description: ""
baseurl: ""
url: "http://sanshui.github.io"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

