# Site settings
title: test
description: ""
baseurl: ""
url: "http://sanshui.github.io"
github_username:  sanshuiyang

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

