# Site settings
title: 三水
email: ymh9509@163.com
description: "三生万物 上善若水"
baseurl: ""
url: "http://sanshui.github.io"

github_username : sanshuiyang

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

